feat(#20): Add Icon component to web
legaplan/design-system pull request #32
Opened 2024-10-30 22:23 UTC by felipe-Ma1a

2024-10-30 22:54 UTC, lucasca2 requested changes

2024-10-30 22:54 UTC, lucasca2 commented on src/web/src/components/Icon/commons/LogOut01.tsx
> +const LogOut01 = () => {
Nunca é pra pegar os icones direto da página, sempre tem q ir em `Go to main component` e pegar da página principal lá

https://www.figma.com/design/f35fmFOuUOX0JYh0J68l5j/%E2%9D%96-Untitled-UI-%E2%80%93-PRO-VARIABLES-(v5.0?node-id=3463-405222&m=dev

2024-10-30 22:54 UTC, lucasca2 commented on src/web/src/components/Icon/commons/LogOut01.tsx
> +      height="20"
Geralmente a `viewbox` é 24px por 24px se n for isso, desconfia que tu pegou do lugar errado

2024-10-30 22:54 UTC, lucasca2 commented on src/web/src/components/Icon/Icon.module.scss
> +}
Aqui é onde a gnt vai fazer a lógica que diminuir proporcionalmente o tamanho da borda do icon, a formula é `size / defaultSize * defaultBorder` no caso a gnt sabe que todos os icones tem a mesma viewBox(`24px`) e a mesma borda(`2px`) entao seria `size / 24 * 2`

Exemplo:
```scss
:root {
  --defaultWidth: 24px;
  --defaultBorder: 2px;
}

.size-2 {
    --size: calc(var(--spaces-3) - var(--spaces-micro));
    svg {
        width: var(--size);
        height: var(--size);
        stroke-width: calc(var(--size) / var(--defaultWidth) * var(--defaultBorder));
        /* 
        * 20px / 24px * 2px = 1.666px;
        * Exatamente como está no figma qnd o Icon tem o tamanho 20x20;
        */
    }
}
```

2024-10-30 22:54 UTC, lucasca2 commented on src/web/src/components/Icon/Icon.module.scss
> +}
Só tem q ver se isso td vai funcionar, na teoria é bonito kkkk

2024-11-01 10:38 UTC, lucasca2 requested changes

2024-11-01 10:38 UTC, lucasca2 commented on src/web/src/components/Icon/commons/Search.tsx
> +};
Esse ícone n foi pego do lugar certo

2024-11-01 10:38 UTC, lucasca2 commented on src/web/src/styles/global.scss
> +
Isso aqui é mt mt específico, é só pro calculo do icon, pode ficar lá dentro do próprio arquivo do icon

2024-11-01 13:54 UTC, felipe-Ma1a commented
@lucasca2 não sei se ta certo mas o search ta como 20x20 no figma

![image](https://github.com/user-attachments/assets/9ba2241f-894d-488a-a3de-8f6b4c4cf3aa)

2024-11-01 23:32 UTC, lucasca2 approved these changes
- [ ] Conferiu se qnd diminui o size ele ta diminuindo o `stroke-width`?

2024-11-02 16:38 UTC, felipe-Ma1a commented
@lucasca2 Testei aqui e o stroke-width não ta diminuindo de acordo com o size, teria que fazer algo assim:

![image](https://github.com/user-attachments/assets/fec1aa40-149d-49fc-bf6f-ce51ab56448c)
![image](https://github.com/user-attachments/assets/9d583241-3979-43c2-9821-534d18778220)

2024-11-02 16:45 UTC, lucasca2 commented
@felipe-Ma1a tenta estilizar o `path` entao invés do `svg`
 
 ```scss
svg > path { ... }
```

2024-11-02 16:53 UTC, felipe-Ma1a commented
> @felipe-Ma1a tenta estilizar o `path` entao invés do `svg`
> 
> ```css-scss
> svg > path { ... }
> ```

Testei as variações com o path mas deu na mesma coisa aqui

![image](https://github.com/user-attachments/assets/fe945494-c38e-4423-bf0b-a55a6dfbaa9a)
![image](https://github.com/user-attachments/assets/796c4639-9adb-43bd-a134-c3bd7ecd83cb)
![image](https://github.com/user-attachments/assets/2366c789-a43e-4d5a-9722-b99214179850)

2024-11-04 23:53 UTC, lucasca2 approved these changes

2024-11-04 23:53 UTC, lucasca2 commented on src/web/src/components/Icon/index.tsx
> +};
Adiciona um `TODO` só pra gnt n esquecer que isso tem q ser mudado em breve
```suggestion
// TODO: Get from theme when it's available
const sizes = {
  1: 16,
  2: 20,
  3: 24,
};
```

2024-11-05 00:38 UTC, merged